  name: LyraSMP
  main: org.woahhs.Plugin
  version: 0.1
  commands:
    fly:
      description: Your Basic Fly Command!
    gamemode:
      description: Your Basic Gamemode Command!
      aliases:
        - gm
    heal:
      description: Your Basic Heal Command!